# dev configuration (use docker-compose up will use docker-compose.yml and docker-comspoe.override.yml both)
# os: mac
version: "3.7"

services:
    nginx:
        ports:
            - "9920:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/index.html:/usr/share/nginx/html/index.html
        restart: always
    webapi:
        env_file: .docker.env
        restart: always
        ports:
            - "9915:8000"
        expose:
            - "8000"
        volumes:
            - .:/linenotify_api
     
    postgres:
        environment:
            POSTGRES_DB: ${POSTGRESQL_DATABASE}
            POSTGRES_USER: ${POSTGRESQL_USER}
            POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
        ports:
            - '9910:5432'
        volumes:
            - linenotify-postgredb-v:/var/lib/postgresql/data
   
volumes:
    linenotify-postgredb-v:

